DESTINATIONS = [
    {"code": "ireland", "name": "Ireland", "capital": "Dublin", "currency": "EUR", "emoji": "🇮🇪"},
    {"code": "united-kingdom", "name": "United Kingdom", "capital": "London", "currency": "GBP", "emoji": "🇬🇧"},
    {"code": "canada", "name": "Canada", "capital": "Toronto", "currency": "CAD", "emoji": "🇨🇦"},
    {"code": "australia", "name": "Australia", "capital": "Sydney", "currency": "AUD", "emoji": "🇦🇺"},
    {"code": "usa", "name": "United States", "capital": "New York", "currency": "USD", "emoji": "🇺🇸"},
    {"code": "germany", "name": "Germany", "capital": "Berlin", "currency": "EUR", "emoji": "🇩🇪"},
    {"code": "netherlands", "name": "Netherlands", "capital": "Amsterdam", "currency": "EUR", "emoji": "🇳🇱"},
    {"code": "uae", "name": "UAE", "capital": "Dubai", "currency": "AED", "emoji": "🇦🇪"},
    {"code": "new-zealand", "name": "New Zealand", "capital": "Auckland", "currency": "NZD", "emoji": "🇳🇿"},
    {"code": "singapore", "name": "Singapore", "capital": "Singapore", "currency": "SGD", "emoji": "🇸🇬"},
    {"code": "portugal", "name": "Portugal", "capital": "Lisbon", "currency": "EUR", "emoji": "🇵🇹"},
    {"code": "spain", "name": "Spain", "capital": "Madrid", "currency": "EUR", "emoji": "🇪🇸"},
    {"code": "switzerland", "name": "Switzerland", "capital": "Zurich", "currency": "CHF", "emoji": "🇨🇭"},
    {"code": "sweden", "name": "Sweden", "capital": "Stockholm", "currency": "SEK", "emoji": "🇸🇪"},
    {"code": "norway", "name": "Norway", "capital": "Oslo", "currency": "NOK", "emoji": "🇳🇴"},
    {"code": "france", "name": "France", "capital": "Paris", "currency": "EUR", "emoji": "🇫🇷"},
    {"code": "japan", "name": "Japan", "capital": "Tokyo", "currency": "JPY", "emoji": "🇯🇵"},
    {"code": "malaysia", "name": "Malaysia", "capital": "Kuala Lumpur", "currency": "MYR", "emoji": "🇲🇾"},
    {"code": "south-africa", "name": "South Africa", "capital": "Cape Town", "currency": "ZAR", "emoji": "🇿🇦"},
    {"code": "brazil", "name": "Brazil", "capital": "São Paulo", "currency": "BRL", "emoji": "🇧🇷"},
]

ORIGINS = [
    # Europe
    {"code": "romania", "name": "Romania", "emoji": "🇷🇴"},
    {"code": "poland", "name": "Poland", "emoji": "🇵🇱"},
    {"code": "italy", "name": "Italy", "emoji": "🇮🇹"},
    {"code": "portugal", "name": "Portugal", "emoji": "🇵🇹"},
    {"code": "france", "name": "France", "emoji": "🇫🇷"},
    {"code": "germany", "name": "Germany", "emoji": "🇩🇪"},
    {"code": "spain", "name": "Spain", "emoji": "🇪🇸"},
    {"code": "ukraine", "name": "Ukraine", "emoji": "🇺🇦"},
    {"code": "greece", "name": "Greece", "emoji": "🇬🇷"},
    {"code": "hungary", "name": "Hungary", "emoji": "🇭🇺"},
    {"code": "bulgaria", "name": "Bulgaria", "emoji": "🇧🇬"},
    {"code": "serbia", "name": "Serbia", "emoji": "🇷🇸"},
    {"code": "croatia", "name": "Croatia", "emoji": "🇭🇷"},
    {"code": "slovakia", "name": "Slovakia", "emoji": "🇸🇰"},
    {"code": "czech-republic", "name": "Czech Republic", "emoji": "🇨🇿"},
    # Asia
    {"code": "india", "name": "India", "emoji": "🇮🇳"},
    {"code": "philippines", "name": "Philippines", "emoji": "🇵🇭"},
    {"code": "pakistan", "name": "Pakistan", "emoji": "🇵🇰"},
    {"code": "bangladesh", "name": "Bangladesh", "emoji": "🇧🇩"},
    {"code": "sri-lanka", "name": "Sri Lanka", "emoji": "🇱🇰"},
    {"code": "nepal", "name": "Nepal", "emoji": "🇳🇵"},
    {"code": "china", "name": "China", "emoji": "🇨🇳"},
    {"code": "indonesia", "name": "Indonesia", "emoji": "🇮🇩"},
    {"code": "malaysia", "name": "Malaysia", "emoji": "🇲🇾"},
    {"code": "singapore", "name": "Singapore", "emoji": "🇸🇬"},
    {"code": "vietnam", "name": "Vietnam", "emoji": "🇻🇳"},
    {"code": "thailand", "name": "Thailand", "emoji": "🇹🇭"},
    {"code": "japan", "name": "Japan", "emoji": "🇯🇵"},
    {"code": "south-korea", "name": "South Korea", "emoji": "🇰🇷"},
    {"code": "iran", "name": "Iran", "emoji": "🇮🇷"},
    {"code": "iraq", "name": "Iraq", "emoji": "🇮🇶"},
    {"code": "syria", "name": "Syria", "emoji": "🇸🇾"},
    {"code": "lebanon", "name": "Lebanon", "emoji": "🇱🇧"},
    {"code": "jordan", "name": "Jordan", "emoji": "🇯🇴"},
    {"code": "kazakhstan", "name": "Kazakhstan", "emoji": "🇰🇿"},
    # Africa
    {"code": "nigeria", "name": "Nigeria", "emoji": "🇳🇬"},
    {"code": "ghana", "name": "Ghana", "emoji": "🇬🇭"},
    {"code": "kenya", "name": "Kenya", "emoji": "🇰🇪"},
    {"code": "south-africa", "name": "South Africa", "emoji": "🇿🇦"},
    {"code": "ethiopia", "name": "Ethiopia", "emoji": "🇪🇹"},
    {"code": "tanzania", "name": "Tanzania", "emoji": "🇹🇿"},
    {"code": "uganda", "name": "Uganda", "emoji": "🇺🇬"},
    {"code": "senegal", "name": "Senegal", "emoji": "🇸🇳"},
    {"code": "cameroon", "name": "Cameroon", "emoji": "🇨🇲"},
    {"code": "morocco", "name": "Morocco", "emoji": "🇲🇦"},
    # Americas
    {"code": "usa", "name": "United States", "emoji": "🇺🇸"},
    {"code": "canada", "name": "Canada", "emoji": "🇨🇦"},
    {"code": "mexico", "name": "Mexico", "emoji": "🇲🇽"},
    {"code": "brazil", "name": "Brazil", "emoji": "🇧🇷"},
    {"code": "colombia", "name": "Colombia", "emoji": "🇨🇴"},
    {"code": "venezuela", "name": "Venezuela", "emoji": "🇻🇪"},
    {"code": "argentina", "name": "Argentina", "emoji": "🇦🇷"},
    {"code": "jamaica", "name": "Jamaica", "emoji": "🇯🇲"},
    {"code": "trinidad", "name": "Trinidad & Tobago", "emoji": "🇹🇹"},
    {"code": "peru", "name": "Peru", "emoji": "🇵🇪"},
    # Oceania + Anglo
    {"code": "australia", "name": "Australia", "emoji": "🇦🇺"},
    {"code": "new-zealand", "name": "New Zealand", "emoji": "🇳🇿"},
    {"code": "ireland", "name": "Ireland", "emoji": "🇮🇪"},
    {"code": "united-kingdom", "name": "United Kingdom", "emoji": "🇬🇧"},
    {"code": "fiji", "name": "Fiji", "emoji": "🇫🇯"},
]
